fields:
  - name: id
    type: integer
    min: 1
    max: 1000
    unique: true
  - name: name
    type: string
    pattern: /^[A-Za-z]{5,15}$/
  - name: email
    type: string
    format: email
    prefix: user.
    suffix: "@example.com"
  - name: age
    type: integer
    distribution:
      type: gaussian
      mean: 35
      std_dev: 10
  - name: state
    type: string
    options: [California, New York, Texas, Florida]
  - name: city
    type: string
    dependencies:
      state: [California, New York]
      city: [Los Angeles, San Francisco, New York City]
  - name: is_employed
    type: boolean
    default: false
  - name: salary
    type: float
    distribution:
      type: uniform
      min: 30000
      max: 100000
